<?php

/**
 * Implements hook_permission().
 */
function module_test_permission() {
  return array(
    'module_test perm' => t('example perm for module_test module'),
  );
}

/**
 * Implements hook_system_info_alter().
 *
 * Manipulate module dependencies to test dependency chains.
 */
function module_test_system_info_alter(&$info, $file, $type) {
  if (Drupal::state()->get('module_test.dependency') == 'missing dependency') {
    if ($file->name == 'forum') {
      // Make forum module depend on ban.
      $info['dependencies'][] = 'ban';
    }
    elseif ($file->name == 'ban') {
      // Make ban depend on a made-up module.
      $info['dependencies'][] = 'foo';
    }
  }
  elseif (Drupal::state()->get('module_test.dependency') == 'dependency') {
    if ($file->name == 'forum') {
      // Make the forum module depend on ban.
      $info['dependencies'][] = 'ban';
    }
    elseif ($file->name == 'ban') {
      // Make ban depend on php module.
      $info['dependencies'][] = 'php';
    }
  }
  elseif (Drupal::state()->get('module_test.dependency') == 'version dependency') {
    if ($file->name == 'forum') {
      // Make the forum module depend on ban.
      $info['dependencies'][] = 'ban';
    }
    elseif ($file->name == 'ban') {
      // Make ban depend on a specific version of php module.
      $info['dependencies'][] = 'php (1.x)';
    }
    elseif ($file->name == 'php') {
      // Set php module to a version compatible with the above.
      $info['version'] = '8.x-1.0';
    }
  }
  if ($file->name == 'seven' && $type == 'theme') {
    $info['regions']['test_region'] = t('Test region');
  }
}

/**
 * Implements hook_hook_info().
 */
function module_test_hook_info() {
  $hooks['test_hook'] = array(
    'group' => 'file',
  );
  return $hooks;
}

/**
 * Implements hook_menu().
 */
function module_test_menu() {
  $items['module-test/hook-dynamic-loading-invoke'] = array(
    'title' => 'Test hook dynamic loading (invoke)',
    'page callback' => 'module_test_hook_dynamic_loading_invoke',
    'access arguments' => array('access content'),
  );
  $items['module-test/hook-dynamic-loading-invoke-all'] = array(
    'title' => 'Test hook dynamic loading (invoke_all)',
    'page callback' => 'module_test_hook_dynamic_loading_invoke_all',
    'access arguments' => array('access content'),
  );
  $items['module-test/hook-dynamic-loading-invoke-all-during-load/%module_test'] = array(
    'title' => 'Test hook dynamic loading (menu item load)',
    'page callback' => 'module_test_hook_dynamic_loading_invoke_all_during_load',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );
  $items['module-test/class-loading'] = array(
    'title' => 'Test loading a class from another module',
    'page callback' => 'module_test_class_loading',
    'access callback' => TRUE,
  );
  $items['module-test/class-loading/psr0-underscores'] = array(
    'title' => 'Test PSR-0 underscore handling',
    'page callback' => 'module_test_class_loading_psr0_underscores',
    'access callback' => TRUE,
  );
  $items['module-test/class-loading/psr0-multi-include'] = array(
    'title' => 'Test PSR-0 multi includes',
    'page callback' => 'module_test_class_loading_psr0_multi_include',
    'access callback' => TRUE,
  );
  $items['module-test/class-loading/psr0-prefix-clash'] = array(
    'title' => 'Test PSR-0 prefix clash',
    'page callback' => 'module_test_class_loading_psr0_prefix_clash',
    'access callback' => TRUE,
  );
  $items['module-test/class-loading/psrx'] = array(
    'title' => 'Test PSR-X class loading',
    'page callback' => 'module_test_class_loading_psrx',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Page callback for 'hook dynamic loading' test.
 *
 * If the hook is dynamically loaded correctly, the menu callback should
 * return 'success!'.
 */
function module_test_hook_dynamic_loading_invoke() {
  $result = module_invoke('module_test', 'test_hook');
  return $result['module_test'];
}

/**
 * Page callback for 'hook dynamic loading' test.
 *
 * If the hook is dynamically loaded correctly, the menu callback should
 * return 'success!'.
 */
function module_test_hook_dynamic_loading_invoke_all() {
  $result = module_invoke_all('test_hook');
  return $result['module_test'];
}

/**
 * Page callback for 'hook dynamic loading' test.
 *
 * If the hook is dynamically loaded correctly, the menu callback should
 * return 'success!'.
 */
function module_test_hook_dynamic_loading_invoke_all_during_load($param) {
  return $param;
}

/**
 * Load function used by module_test_hook_dynamic_loading_invoke_all_during_load().
 *
 * @see module_test_menu().
 */
function module_test_load($param) {
  $result = module_invoke_all('test_hook');
  return $result[$param];
}

/**
 * Page callback for 'class loading' test.
 *
 * This module does not have a dependency on module_autoload_test.module. If
 * that module is enabled, this function should return the string
 * 'Drupal\\module_autoload_test\\SomeClass::testMethod() was invoked.'. If
 * that module is not enabled, this function should return nothing.
 */
function module_test_class_loading() {
  if (class_exists('Drupal\module_autoload_test\SomeClass')) {
    $obj = new Drupal\module_autoload_test\SomeClass();
    return $obj->testMethod();
  }
}

/**
 * Page callback for 'module-test/class-loading/psr0-underscores'.
 */
function module_test_class_loading_psr0_underscores() {
  $pieces = array();
  if (class_exists('Drupal\module_autoload_test\ExistingClass_WithUnderscore')) {
    $pieces[] = 'A class with underscores was found.';
  }
  if (!class_exists('Drupal\module_autoload_test\UnloadableClass_WithUnderscore')) {
    $pieces[] = 'A file with underscores was not included.';
  }
  return implode('<br/>', array_filter($pieces));
}

/**
 * Page callback for 'module-test/class-loading/psr0-multi-include'.
 */
function module_test_class_loading_psr0_multi_include() {
  class_exists('Drupal\module_autoload_test\SubNamespace\SomeClass');
  class_exists('Drupal\module_autoload_test\SubNamespace_SomeClass');
  // If we get here, the application did not crash.
  return 'The application did not crash.';
}

/**
 * Page callback for 'module-test/class-loading/psr0-prefix-clash'.
 */
function module_test_class_loading_psr0_prefix_clash() {
  // The class is defined in the lib folder of module_autoload_test, but we
  // expect the class loader to ignore that file.
  if (!class_exists('Drupal\module_autoload_test_subnamespace\PrefixTestClass')) {
    return 'A file was not included because it is in the wrong folder.';
  }
}

/**
 * Page callback for 'module-test/class-loading/psrx'.
 */
function module_test_class_loading_psrx() {
  $pieces = array();
  if (class_exists('Drupal\module_autoload_test\SomeClassPSRX')) {
    $pieces[] = 'SomeClassPSRX was found.';
  }
  if (class_exists('Drupal\module_autoload_test\ClassWith_Underscore_PSRX')) {
    $pieces[] = 'ClassWith_Underscore_PSRX was found.';
  }
  if (class_exists('Drupal\module_autoload_test\SubNamespacePSRX\SomeClass')) {
    $pieces[] = 'Class in sub-namespace was found.';
  }
  return implode('<br/>', array_filter($pieces));
}

/**
 * Implements hook_modules_enabled().
 */
function module_test_modules_enabled($modules) {
  // Record the ordered list of modules that were passed in to this hook so we
  // can check that the modules were enabled in the correct sequence.
  Drupal::state()->set('system_test.module_enable_order', $modules);
}

/**
 * Implements hook_modules_disabled().
 */
function module_test_modules_disabled($modules) {
  // Record the ordered list of modules that were passed in to this hook so we
  // can check that the modules were disabled in the correct sequence.
  Drupal::state()->set('module_test.disable_order', $modules);
}

/**
 * Implements hook_modules_uninstalled().
 */
function module_test_modules_uninstalled($modules) {
  // Record the ordered list of modules that were passed in to this hook so we
  // can check that the modules were uninstalled in the correct sequence.
  Drupal::state()->set('module_test.uninstall_order', $modules);
}
