<?php

/**
 * @file
 * Drupal-specific autoload.php to be used instead of the one generated by
 * Composer.
 * Having a Drupal-specific autoload.php makes it easier to use a ClassLoader
 * implementation different from the one provided by Composer.
 */

// Use the autoload.php generated by Composer.
return require __DIR__ . '/vendor/autoload.php';
