<?php

/**
 * @file
 * Drupal-specific autoload.php to be used instead of the one generated by
 * Composer.
 * Having a Drupal-specific autoload.php makes it easier to use a ClassLoader
 * implementation different from the one provided by Composer.
 */

use Drupal\Core\Autoload\DrupalAutoloaderInit;

require_once __DIR__ . '/lib/Drupal/Core/Autoload/DrupalAutoloaderInit.php';

return DrupalAutoloaderInit::getLoader();
